apiVersion: apps/v1
kind: Deployment
metadata:
  name: meg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meg
  template:
    metadata:
      labels:
        app: meg
    spec:
      containers:
      - image: okteto.dev/meg:latest
        name: meg
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "d3777786-26ea-4be8-9d82-9c708480447e"
        - name: Vless_Path
          value: "/hygmbmrcesgtd"
        - name: Vmess_UUID
          value: "d3777786-26ea-4be8-9d82-9c708480447e"
        - name: Vmess_Path
          value: "/pkmrhewsxzkhnfx"
        - name: Share_Path
          value: "/v2link"
